version: '3.9'
services:
  mongo:
    image: mongo:7
    container_name: primetrade_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: primetrade_backend
    env_file: ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/primetrade
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: primetrade_frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
